language: node_js
node_js:
  - '8'

script:
  - npm run build

after_success:
  - npm i -g semantic-release
  - NPM_CONFIG_LOGLEVEL=verbose semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email: false